version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.18.1
      - image: cimg/base:2022.11
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
    parallelism: 4

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run:
          name: install dockerize # This is a utility that will attempt to connect to a database, in place of an application for this sample.
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db # If no database is found in 1 minute the job will fail.
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: go test
  

workflows:
  build_dockerDB:
    jobs:
      - build